#!/usr/bin/env bash

cd `dirname "$0"`

cmd=$1

case $cmd in
nginx_reload|nginx_restart)
    vagrant ssh -c "sudo service nginx restart" -- -q
    ;;
mysql_reload|mysql_restart)
    vagrant ssh -c "sudo service mysql restart" -- -q
    ;;
fpm_reload|fpm_restart)
    vagrant ssh -c "sudo service php5.6-fpm restart" -- -q
    vagrant ssh -c "sudo service php7.3-fpm restart" -- -q
    ;;
php5_cli)
    vagrant ssh -c "php5.6 -a" -- -q
    ;;
php7_cli)
    vagrant ssh -c "php7.3 -a" -- -q
    ;;
set_php5)
    vagrant ssh -c "sudo update-alternatives --set php /usr/bin/php5.6" -- -q
    ;;
set_php7)
    vagrant ssh -c "sudo update-alternatives --set php /usr/bin/php7.3" -- -q
    ;;
php|php_cli)
    vagrant ssh -c "php -a" -- -q
    ;;
mysql|mysql_cli)
    vagrant ssh -c "mysql -uroot -proot -h127.0.0.1" -- -q
    ;;
ssh)
    vagrant ssh -- -q
    ;;
reload|restart)
    vagrant halt -f
    vagrant up
    ;;
*)
    echo 'Usage: launcher command'
    echo ''
    echo 'Available commands:'
    echo '  nginx_reload  nginx_restart   Restart nginx web server'
    echo '  mysql_reload  mysql_restart   Restart MySQL database server'
    echo '  fpm_reload    fpm_restart     Restart PHP fpm'
    echo '  php5_cli                      Run PHP 5.x CLI'
    echo '  php7_cli                      Run PHP 7.x CLI'
    echo '  php           php_cli         Run default PHP CLI'
    echo '  set_php5                      Set PHP 5.x as the default PHP executable'
    echo '  set_php7                      Set PHP 7.x as the default PHP executable'
    echo '  mysql         mysql_cli       Run MySQL CLI'
    echo '  ssh                           Run SSH session'
    echo '  reload        restart         Force reload'
esac
