#!/usr/bin/php
<?php
	$mail_path = '/srv/log/sendmail/';
	@mkdir($mail_path);
	$input = file_get_contents('php://stdin');
	$name = str_replace('.', '', (string) microtime(true)) . '.eml';
	file_put_contents($mail_path . $name, $input);
